Milestone #6 Friendships v2
mricanho/stay-in-touch pull request #5
Opened 2021-02-13 05:35 UTC by mricanho

In this milestone, we implement friendships with 2 rows for mutual friendship.

2021-02-13 09:13 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @mricanho and @harshdeepkanhai 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Please implement friendships with 2 rows for mutual friendship ( for understanding read[this artcile](https://explainextended.com/2009/03/07/selecting-friends) and [stackoverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table))
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-02-13 16:38 UTC, mricanho commented
> # Status: REQUIRED CHANGES  
> Hi @mricanho and @harshdeepkanhai
> Such a remarkable project you made! Awesome README!
> We, however, do have a few changes to carry out before we proceed (see review comment).
> 
> For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below and work on the suggested changes.
> 
> * [x]  Please implement friendships with 2 rows for mutual friendship ( for understanding read[this artcile](https://explainextended.com/2009/03/07/selecting-friends) and [stackoverflow discussion](https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table))
> 
> * **When you have made the specified changes, please submit another code review. Thank you!**
> 
> **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
> HAPPY CODING 
> **[Umair Arshad](https://umairarshad.me/)**
> [Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

HI! 

I already implement the 2 rows since the last milestone, to work with two rows I build the update method of the friendships controller and with the help of another code in user helpers and friendship helper, generates a new record that the status gets changed to true.the code is in:

```
`#controllers/friendships_controller.rb

     def update
       @friendship = Friendship.find(params[:id])
       @friendship.update_attribute(:status, true)
       @friendship_two = Friendship.new(user_id: @friendship.friend_id, friend_id: @friendship.user_id, status: true)
       @friendship_two.save
       flash[:notice] = 'Friendship has been accepted'
       friendship_redirect
     end
`

#app/helpers/friendships_helper.rb
module FriendshipsHelper
  def verify_friendship(friend_id)
    Friendship.where('(user_id = ? and friend_id = ?) OR (user_id = ? and friend_id = ?)',
                     current_user.id, friend_id, friend_id, current_user.id).first
  end

  def friendship_button(user)
    friendship = verify_friendship(user)
    if friendship.nil?
      content_tag(:div,
                  (button_to 'Invite to be friends',
                             friendships_path(params: { friendship: { friend_id: user.id, user_id: current_user.id } }),
                             method: :post, class: 'button-friendship'), class: 'button-friendship')
    elsif friendship.status

    elsif friendship.user_id == user.id
      content_tag(:div, (button_to 'Accept Friendship', friendship_path(friendship.id), method: :put) +
                          (button_to 'Reject Friendship', friendship_path(friendship.id), method: :delete))
    else
      content_tag(:p, 'Pending Response', class: 'button-friendship status pending')
    end
  end
end
```
  ```
#app/helpers/user_helper.rb
  
  def friends_and_i
    list = current_user.friendships.map { |x| x.friend_id if x.status }
    list += current_user.inverse_friendships.map { |x| x.user_id if x.status }
    list += [current_user.id]
    list
  end

  def requested_and_received
    list = current_user.friendships.map { |x| x.friend_id if x.status.nil? }
    list += current_user.inverse_friendships.map { |x| x.user_id if x.status.nil? }
    User.where(id: list)
  end
```

Greetings!!!

2021-02-13 18:50 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
I think we might be missing something in the way you've tried to implement Friendships V2.0.

In your response to the previous TSE you post a snippet of code from your user_helper.rb file. In this piece of code, you seem to be pieceing together a complete list of friends IDs from multiple map filters. This is not the intended way of working in friendships V2.0

Please refer to this example, to better understand how we are expected to use double friendship rows in order to query complete lists of friends without having to piece them together from multiple queries or maps:

https://github.com/voscarmv/ror-social-scaffold/pull/3/commits/bb355e85c086ca345a297ea7bced42406af35b4b#diff-3ce1e0cbd5f25d08bd033ba490fa5e87aa43e1abd54e1c9b017d2a4f06cfa8c1

With double friendship rows, we should be able to run a single query, and obtain a full list of friends, with something similar to this:

https://github.com/voscarmv/ror-social-scaffold/pull/3/commits/06896ca182ff2d4905d152f712a20bc30c325c65

If you have difficulty understanding these examples, please take some time to review the suggested articles by the previous TSE. If you still experience trouble, feel free to contact me on slack. My name is Oscar Mier.


### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-13 23:10 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Miguel Ricaño Romero & Kanhai Kanhai ** 
Good job with the improvement for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Don't overuse rubocop disable
- [x] Add integration tests to your project
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-02-14 04:35 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello Miguel Ricaño Romero & Kanhai Kanhai, you've got an impressive project here.

I love the way you used the `content_tag in your helper` and the notification icon. nicely done. 👍  👏 👏  👏  

#### You may have broken a few things while fixing some requested changes.
Let's fix it and we'll be done.

- [ ] Your users page is throwing an error. 
<img width="1423" alt="Screen Shot 2021-02-14 at 4 54 11 AM" src="https://user-images.githubusercontent.com/5264771/107868239-0941a400-6e83-11eb-8e07-58c7f385112b.png">.  There is no need to call the User model from there since you already did that in your users controller `@users`. Refactoring your helper method to accept that users will be more appropriate.
```
  def all_users(users)
    users.reject { |x| x.id == current_user.id }
  end
  ```
  and in your users index view page you can call `all_users(@users).each do |user|`

- [ ] When a friendship request has been accepted, what did you expect to `yield` here. If nothing, just take out the line and your code should be fine.
```     
 ...   
     elsif friendship.status
      yield
     ...
```
<img width="1435" alt="Screen Shot 2021-02-14 at 5 18 32 AM" src="https://user-images.githubusercontent.com/5264771/107868347-1e6b0280-6e84-11eb-9c12-577c6f29ad67.png">

- [ ] I noticed your PR do not have a linter check, kindly fix this too.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or drop a comment here, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-02-14 04:35 UTC, acushlakoncept commented on app/helpers/friendships_helper.rb
>      Friendship.where('(user_id = ? and friend_id = ?) OR (user_id = ? and friend_id = ?)',
[OPTIONAL] You should note methods like this should be better done in your model. 
There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.

2021-02-14 05:44 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-14 05:45 UTC, merged

2021-02-14 07:16 UTC, enaburekhan reviewed
# Status: Project Approved:heavy_check_mark:
**Hi team!
Nice work:clap::clap:. I really like the Greeting, "Hallo Eric".  Keep up the good work.
Move on with your task:walking:.**

Kindly drop your questions here and ping me on slack @ Eric Enaburekhan to respond.
Have a great day:blush:
Eric Enaburekhan